name: Fetch Steam Recently Played Games

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  fetch-games:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Steam Script
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
      run: |
        python steam_recent_games.py

    - name: Commit and Push Changes
      env:
        GITHUB_USERNAME: "ozgurozbek"
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "${{ env.GITHUB_USERNAME }}"
        git config --global user.email "ozgurozbek1@yandex.com"
        git checkout main
        git add README.md
        git commit -m "Update recently played games."
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_USERNAME }}.git main

